### ISSUE TITLE
Difficulty using `formatDate` across time zones

### ISSUE THREAD

**Issue by takempf** [sparkartgroup/handlebars-helper#12]
I'm pretty sure the problems seen in these tests are caused by time zone issues: https://ci.testling.com/SparkartGroupInc/handlebars-helper

What's likely happening is that the helper is being fed a datetime from a certain time zone (like PST), but returns the string based on a different one (like EST). Maybe the `formatDate` helper needs some way to pass the desired time zone/offset.

**Comment by takempf** [comment]
@pushred You mentioned a similar concern, I believe.

**Comment by pushred** [comment]
Isn't `Date.parse` being used ultimately? That's just how it works, converting any given dates into the environment's time. Perhaps [this library](https://github.com/mde/timezone-js) might help.

**Comment by takempf** [comment]
https://github.com/samsonjs/strftime/issues/28
